[package]
name = "synapse-cli"
description = "Command-line interface for Synapse"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "synapse"
path = "src/main.rs"
doc = false

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap.workspace = true
fs2.workspace = true
futures.workspace = true
libc.workspace = true
reflink-copy.workspace = true
serde.workspace = true
serde_json.workspace = true
synapse.workspace = true
tempfile.workspace = true
tokio.workspace = true
unicode-normalization.workspace = true
walkdir.workspace = true

[lints]
workspace = true
